# permissions for end users to view githubreleasesmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-viewer-role
rules:
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
