---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
  - patch
  - update
