apiVersion: github.csye7125-su24-team06/v1
kind: GitHubReleasesMonitor
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-githubreleasesmonitor
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
spec:
  owner: {{ .Values.githubReleasesMonitor.owner }}
  repo: {{ .Values.githubReleasesMonitor.repo }}
  monitorFrom: {{ .Values.githubReleasesMonitor.monitorFrom | default "now" }}
  githubReleaseJobTemplateSpec:
    spec:
      template:
        spec:
          imagePullSecrets: 
          - name: {{ include "helm-cve-operator.fullname" . }}-secrets
          containers:
            - name: {{ .Values.githubReleasesMonitor.githubReleaseJob.image.name }}
              image: "{{ .Values.githubReleasesMonitor.githubReleaseJob.image.repository }}:{{ .Values.githubReleasesMonitor.githubReleaseJob.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.githubReleasesMonitor.githubReleaseJob.image.pullPolicy | default "Always" }}
              envFrom:
                - secretRef:
                    name: {{ include "helm-cve-operator.fullname" . }}-kafka-secrets
                - configMapRef:
                    name: {{ include "helm-cve-operator.fullname" . }}-kafka-configmap
              {{- with .Values.githubReleasesMonitor.githubReleaseJob.image.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
