apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-githubreleasesmonitor-viewer-role
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
