apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-manager-role
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125-su24-team06
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm-cve-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "helm-cve-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
