apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-metrics-reader
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
